apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: cloud-native-app      
spec:
  replicas: 2                 
  selector:                   
    matchLabels:
      app: cloud-native-app
  template:                   
    metadata:
      labels:
        app: cloud-native-app
    spec:
      containers:
      - name: cloud-native-app
        image: 905418307151.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:<IMAGE_TAG>  # Placeholder for image tag
        imagePullPolicy: Always  
        ports:
        - containerPort: 3000    
