apiVersion: v1               
kind: Service                # Declares the resource type as Service
metadata:
  name: cloud-native-app-service  # Name of the Service
spec:
  type: LoadBalancer         # Service type to expose externally
  selector:                  # Targets pods with specific labels
    app: cloud-native-app
  ports:
  - protocol: TCP
    port: 80                 # Port exposed to external clients
    targetPort: 3000         # Port the pods listen on
