name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  # Job 1: Run CDK Diff
  run-cdk-diff:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Run CDK Diff to Check for Infrastructure Changes
    - name: Run CDK Diff
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "Running CDK diff to identify infrastructure changes..."
        npm install -g aws-cdk
        npm install --prefix Infrastructure
        cd Infrastructure
        cdk diff

  # Job 2: Deploy and Build Steps (requires approval)
  deploy-and-build:
    needs: run-cdk-diff
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Packages
    - name: Install Packages
      run: |
        echo "Installing Packages..."
        npm install -g aws-cdk
        npm install --prefix Infrastructure

    # Step 3: Deploy Infrastructure Changes
    - name: Deploy Infrastructure Changes
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "Deploying Infrastructure changes..."
        cd Infrastructure
        cdk deploy --require-approval never

    # Step 4: Login to AWS ECR
    - name: Login to AWS ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "Logging in to AWS ECR..."
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418307151.dkr.ecr.us-east-1.amazonaws.com/ecr-repo

    # Step 5: Build and Tag Docker Image
    - name: Build Docker Image
      env:
        GIT_COMMIT: ${{ github.sha }}
      run: |
        echo "Building Docker image with tag $GIT_COMMIT..."
        docker build -f ./app/Dockerfile -t cloud-native-app:$GIT_COMMIT ./app
        docker tag cloud-native-app:$GIT_COMMIT 905418307151.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:$GIT_COMMIT

    # Step 6: Push Docker Image to ECR
    - name: Push Docker Image to ECR
      env:
        GIT_COMMIT: ${{ github.sha }}
      run: |
        echo "Pushing Docker image with tag $GIT_COMMIT to ECR..."
        docker push 905418307151.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:$GIT_COMMIT

    # Step 7: Update Deployment YAML with the Latest Image
    - name: Update Deployment YAML
      env:
        GIT_COMMIT: ${{ github.sha }}
      run: |
        echo "Updating deployment.yaml with image tag $GIT_COMMIT..."
        sed -i "s|<IMAGE_TAG>|$GIT_COMMIT|g" k8s/deployment.yaml

    # Step 8: Apply Kubernetes Deployment
    - name: Apply Kubernetes Deployment
      env:
        KUBECONFIG: ${{ runner.temp }}/kubeconfig.yaml
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "Applying Kubernetes deployment..."
        echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
